# Toolchain
TOOLCHAIN := /home/hieuhoangwork/work/BBB/gcc-linaro-6.5.0-2018.12-x86_64_arm-linux-gnueabihf/bin
PREFIX := arm-linux-gnueabihf-
CC := $(TOOLCHAIN)/$(PREFIX)gcc 

all:
	$(CC) -o main main.c 

clean:
	rm -rf main